# Generated by Django 5.0.3 on 2024-08-14 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imageUrl', models.CharField(max_length=1200)),
                ('title', models.CharField(max_length=64)),
                ('discription', models.CharField(max_length=250)),
                ('price', models.FloatField(max_length=8)),
            ],
        ),
    ]
