# Generated by Django 5.0.3 on 2024-09-13 21:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_cart'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='cardItem',
            new_name='cartItem',
        ),
    ]
