# Generated by Django 5.0.3 on 2024-09-13 21:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_rename_carditem_cart_cartitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='cartItem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.product'),
        ),
    ]
