# Generated by Django 5.0.3 on 2024-09-15 04:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_alter_cart_cartitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='cartItem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prosuct', to='store.product'),
        ),
    ]
