# Generated by Django 5.0.3 on 2024-09-15 15:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_alter_cart_cartitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='cartItem',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product', to='store.product'),
        ),
    ]
